# Dependencies
highlighter:         rouge

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: false

# Setup
title:               'Boris Nagaev'
tagline:             'Home page'
description:         'Home page of Boris Nagaev (<a href="https://keybase.io/starius">starius</a>), bnagaev@gmail.com'
url:                 http://starius.ru
baseurl:             /
paginate:            5

# About/contact
author:
  name:              'Boris Nagaev'
  url:               http://starius.ru
  email:             bnagaev@gmail.com

github:
  repo:              https://github.com/starius/starius.github.io
  author:            https://github.com/starius/
